import Link from "next/link";
import { ArrowLeft, Bell, Database, Download, HeartPulse, Link2, ShieldCheck, UserRound, type LucideIcon } from "lucide-react";
import { NuraShell } from "@/components/nura-shell";
import { ProfileSettingsForm } from "@/components/profile-settings-form";
import { getUserAvatarUrl } from "@/lib/avatar";
import { getSessionUser } from "@/lib/integrations/supabase-server";

const copy: Record<string, { title: string; desc: string; Icon: LucideIcon }> = {
 profile:{title:"Profile",desc:"Your basic account details.",Icon:UserRound},
 preferences:{title:"Preferences",desc:"Choose how and when Nura follows up.",Icon:Bell},
 "health-information":{title:"Health information",desc:"The context you choose to keep with Nura.",Icon:HeartPulse},
 memory:{title:"Memory & privacy",desc:"Review what Nura remembers and why.",Icon:Database},
 data:{title:"Data & export",desc:"Download, export or remove your information.",Icon:Download},
 support:{title:"Support & safety",desc:"Safety boundaries and routes to urgent help.",Icon:ShieldCheck},
 connections:{title:"Connected apps",desc:"A frontend preview of future connections.",Icon:Link2},
};
export default async function SettingsSection({params}:{params:Promise<{section:string}>}){const {section}=await params;const user=await getSessionUser();const displayName=(user?.user_metadata?.display_name as string|undefined)||user?.email||"You";const avatarUrl=getUserAvatarUrl(user);const item=copy[section]||copy.preferences;const Icon=item.Icon;return <NuraShell userName={displayName} userAvatarUrl={avatarUrl}><div className="dashboard-page settings-detail-page"><Link href="/me" className="back-link"><ArrowLeft/> Me</Link><header className="settings-detail-head"><span className="settings-hero-icon"><Icon/></span><div><h1>{item.title}</h1><p>{item.desc}</p></div></header>{section==="preferences"&&<div className="settings-panels"><section><h3>Follow-up channel</h3><label className="radio-row"><input type="radio" defaultChecked name="channel"/> WhatsApp <small>Messages and voice check-ins</small></label><label className="radio-row"><input type="radio" name="channel"/> In app <small>Notifications inside Nura</small></label><label className="radio-row"><input type="radio" name="channel"/> Both <small>Use both channels</small></label></section><section><h3>Quiet hours</h3><div className="field-row"><label>From<input defaultValue="22:00" type="time"/></label><label>Until<input defaultValue="07:00" type="time"/></label></div><label className="toggle-row">Allow urgent safety notifications<input type="checkbox" defaultChecked/></label></section><section><h3>Check-in style</h3><select><option>Gentle and concise</option><option>More conversational</option><option>Very brief</option></select></section></div>}
{section==="health-information"&&<div className="settings-panels"><section><h3>Medication context</h3><div className="info-row"><b>Amlodipine 5mg</b><small>User-added · Started 5 days ago</small><button>Edit</button></div><button className="secondary-cta">+ Add medication</button></section><section><h3>Things you’re tracking</h3><div className="chip-cloud"><span>Headaches</span><span>Sleep</span><span>Work stress</span><span>Blood pressure</span></div><button className="secondary-cta">Manage</button></section><section><h3>Care contacts</h3><div className="info-row"><b>Dr Patel</b><small>GP · Example care contact</small><button>Edit</button></div></section></div>}
{section==="memory"&&<div className="settings-panels"><section><h3>What Nura remembers</h3><p className="muted">Memories stay visible and editable. Nura should only retain context you’ve chosen to keep.</p>{["Work can feel especially stressful before early shifts","You prefer evening check-ins after 7 PM","You are monitoring headaches after a GP visit"].map(x=><div className="memory-row" key={x}><span>{x}</span><button>Remove</button></div>)}</section><section><h3>Memory controls</h3><label className="toggle-row">Suggest useful memories after conversations<input type="checkbox" defaultChecked/></label><label className="toggle-row">Use approved memories in follow-ups<input type="checkbox" defaultChecked/></label></section></div>}
{section==="data"&&<div className="settings-panels"><section><h3>Export</h3><p className="muted">Preview actions only. No export is generated in this UI prototype.</p><button className="secondary-cta"><Download/> Export all data</button><button className="secondary-cta"><Download/> Export health summaries</button></section><section className="danger-zone"><h3>Delete data</h3><p>Remove individual Threads or your entire Nura account.</p><button>Delete account</button></section></div>}
{section==="support"&&<div className="settings-panels"><section><h3>Nura’s role</h3><p className="muted">Nura organises, remembers and follows up. It does not diagnose, prescribe, change medication, or replace professional care.</p></section><section><h3>Urgent help</h3><p>If you feel unsafe or symptoms may be urgent, contact emergency or urgent-care services rather than waiting for Nura.</p><button className="primary-cta">View urgent support options</button></section></div>}
{section==="connections"&&<div className="settings-panels"><section><h3>Communication</h3><div className="connection-row"><span>WhatsApp</span><b>UI preview</b><button>Manage</button></div><div className="connection-row"><span>Calendar</span><b>Not connected</b><button>Preview</button></div></section><section><h3>Future health connections</h3><p className="muted">Apple Health, wearables and health-record connections are intentionally not implemented in this frontend prototype.</p></section></div>}
{section==="profile"&&<ProfileSettingsForm displayName={displayName} email={user?.email ?? ""} avatarUrl={avatarUrl}/>}</div></NuraShell>}
