import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, Bell, Database, Download, HeartPulse, Link2, ShieldCheck, UserRound, type LucideIcon } from "lucide-react";
import { NuraShell } from "@/components/nura-shell";
import { ProfileSettingsForm } from "@/components/profile-settings-form";
import { PreferencesChannelForm } from "@/components/preferences-channel-form";
import { PushNotificationsToggle } from "@/components/push-notifications-toggle";
import { DeleteAccountButton } from "@/components/delete-account-button";
import { getUserAvatarUrl } from "@/lib/avatar";
import { getSessionUser, getSupabaseSessionClient } from "@/lib/integrations/supabase-server";

const copy: Record<string, { title: string; desc: string; Icon: LucideIcon }> = {
 profile:{title:"Profile",desc:"Your basic account details.",Icon:UserRound},
 preferences:{title:"Preferences",desc:"Choose how and when Nura follows up.",Icon:Bell},
 "health-information":{title:"Health information",desc:"The context you choose to keep with Nura.",Icon:HeartPulse},
 memory:{title:"Memory & privacy",desc:"Review what Nura remembers and why.",Icon:Database},
 data:{title:"Data & export",desc:"Download, export or remove your information.",Icon:Download},
 support:{title:"Support & safety",desc:"Safety boundaries and routes to urgent help.",Icon:ShieldCheck},
 connections:{title:"Connected apps",desc:"A frontend preview of future connections.",Icon:Link2},
};
export default async function SettingsSection({params}:{params:Promise<{section:string}>}){const {section}=await params;if(section==="billing")redirect("/billing");const supportEmail=process.env.SUPPORT_EMAIL||"support@nura.app";const user=await getSessionUser();const displayName=(user?.user_metadata?.display_name as string|undefined)||user?.email||"You";const avatarUrl=getUserAvatarUrl(user);const item=copy[section]||copy.preferences;const Icon=item.Icon;let phone="";let preferredChannel="whatsapp";if((section==="profile"||section==="preferences")&&user){const supabase=await getSupabaseSessionClient();const {data}=await supabase.from("nura_profiles").select("phone, preferred_channel").eq("id",user.id).maybeSingle();phone=data?.phone||"";preferredChannel=data?.preferred_channel||"whatsapp";}return <NuraShell userName={displayName} userAvatarUrl={avatarUrl}><div className="dashboard-page settings-detail-page"><Link href="/me" className="back-link"><ArrowLeft/> Me</Link><header className="settings-detail-head"><span className="settings-hero-icon"><Icon/></span><div><h1>{item.title}</h1><p>{item.desc}</p></div></header>{section==="preferences"&&<div className="settings-panels"><PreferencesChannelForm initialChannel={preferredChannel}/><PushNotificationsToggle/><section><h3>Quiet hours <span className="preview-badge">Coming soon</span></h3><div className="field-row"><label>From<input defaultValue="22:00" type="time" disabled/></label><label>Until<input defaultValue="07:00" type="time" disabled/></label></div><label className="toggle-row">Allow urgent safety notifications<input type="checkbox" defaultChecked disabled/></label></section><section><h3>Check-in style <span className="preview-badge">Coming soon</span></h3><select disabled><option>Gentle and concise</option><option>More conversational</option><option>Very brief</option></select></section></div>}
{section==="health-information"&&<div className="settings-panels"><p className="muted preview-note">Example layout — editing medications, tracked topics and care contacts here isn&apos;t wired up yet. Share this context with Nura in a conversation instead.</p><section><h3>Medication context</h3><div className="info-row"><b>Amlodipine 5mg</b><small>User-added · Started 5 days ago</small><button disabled>Edit</button></div><button className="secondary-cta" disabled>+ Add medication</button></section><section><h3>Things you’re tracking</h3><div className="chip-cloud"><span>Headaches</span><span>Sleep</span><span>Work stress</span><span>Blood pressure</span></div><button className="secondary-cta" disabled>Manage</button></section><section><h3>Care contacts</h3><div className="info-row"><b>Dr Patel</b><small>GP · Example care contact</small><button disabled>Edit</button></div></section></div>}
{section==="memory"&&<div className="settings-panels"><p className="muted preview-note">Example layout — removing individual memories here isn&apos;t wired up yet.</p><section><h3>What Nura remembers</h3><p className="muted">Memories stay visible and editable. Nura should only retain context you’ve chosen to keep.</p>{["Work can feel especially stressful before early shifts","You prefer evening check-ins after 7 PM","You are monitoring headaches after a GP visit"].map(x=><div className="memory-row" key={x}><span>{x}</span><button disabled>Remove</button></div>)}</section><section><h3>Memory controls</h3><label className="toggle-row">Suggest useful memories after conversations<input type="checkbox" defaultChecked disabled/></label><label className="toggle-row">Use approved memories in follow-ups<input type="checkbox" defaultChecked disabled/></label></section></div>}
{section==="data"&&<div className="settings-panels"><section><h3>Export</h3><p className="muted">Download everything Nura has stored for your account - Threads, messages, check-ins, and shared documents - as a single JSON file.</p><a href="/api/account/export" className="secondary-cta"><Download/> Export all data</a></section><section className="danger-zone"><h3>Delete data</h3><p className="muted">Permanently remove your entire Nura account and everything in it. This cannot be undone.</p><DeleteAccountButton/></section></div>}
{section==="support"&&<div className="settings-panels"><section><h3>Nura’s role</h3><p className="muted">Nura organises, remembers and follows up. It does not diagnose, prescribe, change medication, or replace professional care.</p></section><section><h3>Urgent help</h3><p className="muted">If you feel unsafe or symptoms may be urgent, contact emergency or urgent-care services rather than waiting for Nura.</p></section><section><h3>Contact support</h3><p className="muted">Questions, account issues, or something not working as expected — email us and we&apos;ll get back to you.</p><a href={`mailto:${supportEmail}`} className="secondary-cta">{supportEmail}</a></section></div>}
{section==="connections"&&<div className="settings-panels"><section><h3>Communication</h3><div className="connection-row"><span>WhatsApp</span><b>UI preview</b><button>Manage</button></div><div className="connection-row"><span>Calendar</span><b>Not connected</b><button>Preview</button></div></section><section><h3>Future health connections</h3><p className="muted">Apple Health, wearables and health-record connections are intentionally not implemented in this frontend prototype.</p></section></div>}
{section==="profile"&&<ProfileSettingsForm displayName={displayName} email={user?.email ?? ""} avatarUrl={avatarUrl} phone={phone}/>}</div></NuraShell>}
