"use client";

import { useState } from "react";
import { FileText, LockKeyhole, MessageCircle, Mic, ShieldCheck, UserRound } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PrototypeAction } from "@/components/prototype-action";

const tabs = [
  { id: "connection", label: "Connection", icon: MessageCircle },
  { id: "voice", label: "Voice & reminders", icon: Mic },
  { id: "memory", label: "Memory & context", icon: UserRound },
  { id: "uploads", label: "Uploads", icon: FileText },
  { id: "privacy", label: "Privacy & data", icon: LockKeyhole },
  { id: "support", label: "Support & safety", icon: ShieldCheck },
] as const;

type TabId = (typeof tabs)[number]["id"];

function Action({label,title,description,primary=false}:{label:string;title:string;description:string;primary?:boolean}){
 return <PrototypeAction label={label} title={title} description={description} className={`app-btn ${primary?"primary":"outline"}`}/>;
}

function SettingsRows({ active }: { active: TabId }) {
  const [voiceOn,setVoiceOn]=useState(true);
  if (active === "connection") return <><h2>Connection</h2><p className="muted">Manage how Sage reaches you for check-ins.</p><div className="setting-row"><div><b>WhatsApp</b><span>+44 7123 456789 · Connected</span></div><Action label="Manage" title="Manage WhatsApp connection" description="Change, disconnect or reconnect the WhatsApp number used by Sage."/></div><div className="setting-row"><div><b>Connection status</b><span>Sage can currently send scheduled WhatsApp check-ins.</span></div><span className="channel-pill">Connected</span></div><div className="setting-row"><div><b>Reconnect number</b><span>Change the WhatsApp number connected to this account.</span></div><Action label="Reconnect" title="Reconnect WhatsApp" description="A reconnect flow will be connected to the WhatsApp provider during integration."/></div></>;
  if (active === "voice") return <><h2>Voice & reminders</h2><p className="muted">Choose how Sage speaks with you and when reminders arrive.</p><div className="setting-row"><div><b>Voice check-ins</b><span>Allow Sage to use voice for scheduled check-ins.</span></div><button type="button" aria-pressed={voiceOn} aria-label="Toggle voice check-ins" className={`toggle prototype-toggle ${voiceOn?"":"off"}`} onClick={()=>setVoiceOn(v=>!v)}/></div><div className="setting-row"><div><b>Preferred voice</b><span>Warm, calm and conversational.</span></div><Action label="Change voice" title="Choose Sage’s voice" description="Preview and select the voice Sage will use for voice check-ins."/></div><div className="setting-row"><div><b>Reminder timing</b><span>Send a gentle reminder before a scheduled check-in.</span></div><Action label="30 minutes" title="Reminder timing" description="Choose how long before a check-in Sage should remind you."/></div><div className="setting-row"><div><b>Quiet hours</b><span>Sage will avoid non-urgent check-ins during this period.</span></div><Action label="10 PM – 7 AM" title="Quiet hours" description="Adjust the time range when Sage should avoid non-urgent messages."/></div></>;
  if (active === "memory") return <><h2>Memory & context</h2><p className="muted">Review and control what Sage remembers across your plans.</p><div className="setting-row"><div><b>Personal context</b><span>Sleep difficulty, work stress and preferred check-in style.</span></div><Action label="Review" title="Personal context" description="Review the personal context currently available to Sage."/></div><div className="setting-row"><div><b>Health guidance</b><span>GP advice and plan-related notes Sage currently references.</span></div><Action label="View context" title="Health guidance context" description="Preview the health guidance and notes attached to your plans."/></div><div className="setting-row"><div><b>Memory controls</b><span>Choose what Sage can keep, forget or stop using.</span></div><Action label="Manage memory" title="Memory controls" description="Choose which remembered context Sage may continue using."/></div></>;
  if (active === "uploads") return <><h2>Uploads</h2><p className="muted">Manage files you have shared to give Sage more context.</p><div className="setting-row"><div><b>GP note.pdf</b><span>PDF · Added during onboarding</span></div><Action label="View" title="GP note.pdf" description="Frontend preview for the uploaded GP note."/></div><div className="setting-row"><div><b>therapy-goals.jpg</b><span>Image · Added to wellbeing context</span></div><Action label="View" title="therapy-goals.jpg" description="Frontend preview for the uploaded image."/></div><div className="setting-row"><div><b>Add more context</b><span>Upload another document, screenshot or note.</span></div><Action primary label="Upload file" title="Upload context" description="Drag and drop or choose a file in the final integrated flow."/></div></>;
  if (active === "privacy") return <><h2>Privacy & data</h2><p className="muted">Control your information, exports and stored Sage data.</p><div className="setting-row"><div><b>Download your data</b><span>Export your plans, context and check-in history.</span></div><Action label="Export data" title="Export your Sage data" description="Preview of the export flow. No data is downloaded in this frontend-only prototype."/></div><div className="setting-row"><div><b>Delete saved context</b><span>Remove information Sage currently remembers.</span></div><Action label="Review data" title="Review saved context" description="Review and select context before deletion."/></div><div className="setting-row"><div><b>Delete account</b><span>Permanently remove your account and stored information.</span></div><Action label="Delete account" title="Delete Sage account?" description="Destructive confirmation UI only. Nothing is deleted in this prototype."/></div></>;
  return <><h2>Support & safety</h2><p className="muted">Get help with Sage and find urgent-support resources.</p><div className="setting-row"><div><b>Help centre</b><span>Find answers about plans, check-ins and account settings.</span></div><Action label="Open help" title="Sage help centre" description="Browse common questions about plans, check-ins, privacy and account controls."/></div><div className="setting-row"><div><b>Contact support</b><span>Get help with your Sage account or experience.</span></div><Action label="Contact us" title="Contact Sage support" description="Frontend contact-support dialog for the hackathon prototype."/></div><div className="setting-row"><div><b>Urgent support</b><span>Sage is not emergency care. Access crisis and urgent-support resources here.</span></div><Action label="View support" title="Urgent support" description="If someone is in immediate danger, they should contact local emergency services. Sage is not emergency care."/></div></>;
}

export default function MePage() {
  const [active, setActive] = useState<TabId>("connection");
  return <AppShell active="Me"><section className="app-width app-main"><div className="page-eyebrow">PROFILE & PREFERENCES</div><h1 className="page-title">Me</h1><p className="page-subtitle">Your connection, preferences, privacy and support controls in one place.</p><div className="settings-grid" style={{marginTop:30}}><aside className="panel settings-menu" role="tablist" aria-label="Profile settings">{tabs.map(({id,label,icon:Icon})=><button key={id} type="button" role="tab" aria-selected={active===id} className={active===id?"active":""} onClick={()=>setActive(id)}><Icon/> {label}</button>)}</aside><section className="panel settings-content" role="tabpanel"><SettingsRows active={active}/></section></div></section></AppShell>;
}