import { CalendarClock, ChevronLeft, ChevronRight, MessageCircle, Mic } from "lucide-react";
import { AppShell, ChannelPill } from "@/components/app-shell";

const cells=[27,28,29,30,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31];
export default function CalendarPage(){return <AppShell active="Calendar"><section className="app-width app-main">
 <div className="section-head"><div><div className="page-eyebrow">CHECK-INS & REMINDERS</div><h1 className="page-title">Calendar</h1><p className="page-subtitle">See every Sage session across your plans in one calm view.</p></div><div className="tabs" style={{margin:0}}><button>Week</button><button className="active">Month</button></div></div>
 <div className="calendar-shell">
  <section className="panel calendar-panel"><div className="calendar-toolbar"><button className="app-btn outline"><ChevronLeft/> </button><h2 style={{fontFamily:'var(--font-display)',fontSize:28,margin:0}}>July 2026</h2><button className="app-btn outline"><ChevronRight/></button></div><div className="calendar-grid">{cells.map((n,i)=><div className={`cal-cell ${i<4?'muted-cell':''}`} key={i}><b>{n}</b>{n===23&&<div className="event">7:00 PM · Sleep reset</div>}{n===24&&<div className="event blue">10:00 AM · Walk check-in</div>}{n===27&&i>4&&<div className="event">6:30 PM · Reflection</div>}</div>)}</div></section>
  <aside className="panel calendar-detail"><div className="panel-label">THURSDAY 23 JULY</div><h3>Sleep reset</h3><p className="muted">Stabilise My Week</p><div className="plan-meta-row"><CalendarClock/> 7:00 PM</div><ChannelPill/><p style={{lineHeight:1.6,marginTop:18}}>A short evening check-in focused on what helped or disrupted your sleep today.</p><button className="app-btn primary" style={{width:'100%',marginTop:12}}><MessageCircle/> Start check-in</button><button className="app-btn outline" style={{width:'100%',marginTop:8}}>Reschedule</button><button className="app-btn outline" style={{width:'100%',marginTop:8}}>Cancel</button></aside>
 </div>
 </section></AppShell>}